apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: custom-nlp-chatbot-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - api.custom-nlp-chatbot.com
    secretName: custom-nlp-chatbot-tls
  rules:
  - host: api.custom-nlp-chatbot.com
    http:
      paths:
      - path: /v1
        pathType: Prefix
        backend:
          service:
            name: custom-nlp-chatbot
            port:
              number: 8000
      - path: /metrics
        pathType: Prefix
        backend:
          service:
            name: custom-nlp-chatbot
            port:
              number: 9100

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: custom-nlp-chatbot-network-policy
spec:
  podSelector:
    matchLabels:
      app: custom-nlp-chatbot
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - protocol: TCP
      port: 9100
  egress:
  - to:
    - ipBlock:
        cidr: 10.0.0.0/8
    ports:
    - protocol: TCP
      port: 6379
