apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-nlp-chatbot
  labels:
    app: custom-nlp-chatbot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: custom-nlp-chatbot
  template:
    metadata:
      labels:
        app: custom-nlp-chatbot
    spec:
      containers:
      - name: chatbot
        image: custom-nlp-chatbot:latest
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: REDIS_HOST
          value: "redis"
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: custom-nlp-chatbot
spec:
  selector:
    app: custom-nlp-chatbot
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: LoadBalancer
